options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2

  # Mixins
  mixins-before-declarations: 2

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks:
    - 2
    - ignore-single-line-rulesets: true
  single-line-per-selector: 2

  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 2
  no-color-literals:
    - 2
    - allow-rgba: true
  no-combinators: 0
  no-css-comments: 0
  no-debug: 0
  no-disallowed-properties: 0
  no-duplicate-properties: 0
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 0
  no-misspelled-properties:
    - 2
    - extra-properties: []
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: true
      allow-element-with-class: true
      allow-element-with-id: false
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 0
  no-universal-selectors: 0
  no-url-domains: 2
  no-url-protocols: 2
  no-vendor-prefixes:
    - 0
    - additional-identifiers: []
      excluded-identifiers: []
  no-warn: 0
  property-units:
    - 2
    - global:
        - ch
        - em
        - ex
        - rem
        - cm
        - in
        - mm
        - pc
        - pt
        - px
        - q
        - vh
        - vw
        - vmin
        - vmax
        - deg
        - grad
        - rad
        - turn
        - ms
        - s
        - Hz
        - kHz
        - dpi
        - dpcm
        - dppx
        - '%'
      per-property: {}

  # Nesting
  declarations-before-nesting: 2
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format:
    - 2
    - convention: hyphenatedlowercase
  function-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  id-name-format:
    - 2
    - convention: hyphenatedlowercase
  mixin-name-format: 0
  placeholder-name-format:
    - 2
    - convention: hyphenatedlowercase

  # Style Guide
  attribute-quotes: 2
  bem-depth:
    - 0
    - max-depth: 2
  border-zero:
    - 2
    - convention: zero
  brace-style:
    - 2
    - style: 'stroustrup'
      allow-single-line: true
  clean-import-paths:
    - 2
    - filename-extension: false
      leading-underscore: false
  empty-args: 0
  hex-length:
    - 2
    - style: short
  hex-notation:
    - 2
    - style: lowercase
  indentation: 0
  leading-zero:
    - 2
    - include: false
  max-line-length: 0
  max-file-line-count: 0
  nesting-depth:
    - 2
    - max-depth: 6
  property-sort-order:
    - 2
    - ignore-custom-properties: true
      order: recess
  pseudo-element: 2
  quotes:
    - 2
    - style: single
  shorthand-values:
    - 2
    - allowed-shorthands:
        - 1
        - 2
        - 3
        - 4
  url-quotes: 2
  variable-for-property: 0
  zero-unit: 2

  # Inner Spacing
  space-after-comma:
    - 2
    - include: true
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace:
    - 2
    - include: true
  space-before-bang:
    - 2
    - include: true
  space-after-bang:
    - 2
    - include: false
  space-between-parens:
    - 2
    - include: false
  space-around-operator: 2

  # Final Items
  trailing-semicolon: 2
  final-newline:
    - 2
    - include: true